package cn.lonecloud.bean;

import java.util.Date;

public class UserData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_Userdata.id
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_Userdata.userId
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_Userdata.dataId
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    private String dataid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_Userdata.precent
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    private Integer precent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_Userdata.url
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_Userdata.path
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_Userdata.createTime
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_Userdata.id
     *
     * @return the value of tbl_Userdata.id
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_Userdata.id
     *
     * @param id the value for tbl_Userdata.id
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_Userdata.userId
     *
     * @return the value of tbl_Userdata.userId
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_Userdata.userId
     *
     * @param userid the value for tbl_Userdata.userId
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_Userdata.dataId
     *
     * @return the value of tbl_Userdata.dataId
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public String getDataid() {
        return dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_Userdata.dataId
     *
     * @param dataid the value for tbl_Userdata.dataId
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public void setDataid(String dataid) {
        this.dataid = dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_Userdata.precent
     *
     * @return the value of tbl_Userdata.precent
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public Integer getPrecent() {
        return precent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_Userdata.precent
     *
     * @param precent the value for tbl_Userdata.precent
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public void setPrecent(Integer precent) {
        this.precent = precent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_Userdata.url
     *
     * @return the value of tbl_Userdata.url
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_Userdata.url
     *
     * @param url the value for tbl_Userdata.url
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_Userdata.path
     *
     * @return the value of tbl_Userdata.path
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_Userdata.path
     *
     * @param path the value for tbl_Userdata.path
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_Userdata.createTime
     *
     * @return the value of tbl_Userdata.createTime
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_Userdata.createTime
     *
     * @param createtime the value for tbl_Userdata.createTime
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}