package cn.lonecloud.dao;

import cn.lonecloud.bean.UserData;
import cn.lonecloud.bean.UserDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_Userdata
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    int countByExample(UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_Userdata
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    int deleteByExample(UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_Userdata
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_Userdata
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    int insert(UserData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_Userdata
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    int insertSelective(UserData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_Userdata
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    List<UserData> selectByExample(UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_Userdata
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    UserData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_Userdata
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserData record, @Param("example") UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_Userdata
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    int updateByExample(@Param("record") UserData record, @Param("example") UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_Userdata
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    int updateByPrimaryKeySelective(UserData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_Userdata
     *
     * @mbggenerated Fri Jun 16 11:52:32 CST 2017
     */
    int updateByPrimaryKey(UserData record);
}